name: Deploys

on:
  release:
    types: [published]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy-pypi:

    runs-on: ubuntu-latest
    environment: Deploys
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: Build and Publish Python Packages
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine      
        python setup.py sdist
        twine upload dist/*
        cd setups/api/
        python setup.py sdist
        twine upload dist/*
        cd ..
        cd gui
        python setup.py sdist
        twine upload dist/*
        cd ..
        cd remote_app
        python setup.py sdist
        twine upload dist/*        
        cd ..
        cd tests
        python setup.py sdist
        twine upload dist/*  
        cd ..
        

  deploy-docker:

    runs-on: ubuntu-latest
    environment: Deploys
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: Build and Publish Docker Images
      env:
        VERSION: ${{ github.event.release.tag_name }}    
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        cd .. 
        docker build -t ghcr.io/naruno/api:latest -f Naruno/docker/local/api/Dockerfile .
        docker build -t ghcr.io/naruno/api:$VERSION -f Naruno/docker/local/api/Dockerfile .  
        docker build -t ghcr.io/naruno/cli:latest -f Naruno/docker/local/cli/Dockerfile .
        docker build -t ghcr.io/naruno/cli:$VERSION -f Naruno/docker/local/cli/Dockerfile .
        docker push ghcr.io/naruno/api:latest
        docker push ghcr.io/naruno/api:$VERSION
        docker push ghcr.io/naruno/cli:latest
        docker push ghcr.io/naruno/cli:$VERSION
