name: Functional Tests

on: 
  push:
    paths:
      - 'docker/local/api/**'
      - 'src/**'  
      - 'requirements/**'
      - 'functional_test/**'
  pull_request:
    paths:
      - 'docker/local/api/**'
      - 'src/**'  
      - 'requirements/**'
      - 'functional_test/**'

jobs: 
  build:
    name: Functional Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and run tests
      run: |
        pip install pytest
        cd ..
        docker build -t decentra-network-api -f Decentra-Network/docker/local/api/Dockerfile .
        pytest Decentra-Network/functional_test/docker/test_decentra_network_docker.py
