name: Gource

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  gource:
    runs-on: ubuntu-latest
    environment: Builds   

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1
        with:
          gource_title: 'Naruno'
          logo_url: 'https://user-images.githubusercontent.com/41792982/222755632-12b6542e-0fbc-437b-b453-4e5cff9cc83d.png'
          gource_resolution: '1080p'
          gource_fps: 60
          gource_font_size: 40


      - name: Zip
        run: zip gource_naruno ./gource/gource.mp4
      - uses: AButler/upload-release-assets@v2.0
        if: github.event_name == 'release'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          files: 'gource_naruno.zip'
      - name: 'Upload gource video'
        uses: actions/upload-artifact@v2
        with:
          name: gource_naruno
          path: gource_naruno.zip
